name: Hello World Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step to print a hello world message
      - name: Say Hello
        run: echo "Hello, World!"

      # Optional step to post a comment on the PR
      - name: Comment on PR with Hello World
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          curl -s -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments \
            -d "{\"body\": \"Hello, World! This is a comment from the GitHub Actions workflow.\"}"
